### ISSUE TITLE
error running servers

### ISSUE THREAD

**Issue by jasgeo75** [satellitecomponent/Neurite#26]
Primary app runs fine, nice work -- but there may be an issue with the servers:

node start_servers.js  
file:///mnt/repos/Neurite/Localhost%20Servers/start_servers.js:1
const { spawn } = require('child_process');
                  ^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/mnt/repos/Neurite/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///mnt/repos/Neurite/Localhost%20Servers/start_servers.js:1:19
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.15.0

**Comment by jasgeo75** [comment]
this seems to be resolvable by changing:
`const { spawn } = require('child_process');`
to:
`import { spawn } from 'child_process';`

**Comment by satellitecomponent** [comment]
> this seems to be resolvable by changing: `const { spawn } = require('child_process');` to: `import { spawn } from 'child_process';`

Thanks for that! I will mention you in the changelog.
