### ISSUE TITLE
Event listeners not restored for saved networks.

### ISSUE THREAD

**Issue by satellitecomponent** [satellitecomponent/Neurite#30]
A not yet implemented improvement is the ability for saved networks to retain their event listeners.

**Comment by jkbrooks** [comment]
Might be able to look at this in a week or two

**Comment by satellitecomponent** [comment]
> Might be able to look at this in a week or two

Sounds great! Let me know if you have any questions. This is a really important issue that I plan on addressing, any progress you make would be of great help!

**Comment by jkbrooks** [comment]
Sorry I haven't been able to help but this project is actively on my radar and I really want to support it, maybe even with a bounty to get dev help.  Will keep you posted if that happens
