### ISSUE TITLE
Auto save the content to local storage at least 

### ISSUE THREAD

**Issue by brandonstack** [satellitecomponent/Neurite#31]
Hi,

Thanks for building such a talented application. I love the idea of fractal workspace of text links.

When I was playing with Neurite, I met two times of data loss accidentally. I accidentally close the browser tab by clicking the close tab shortcut I set before first time. Then I try to explorer the local ai feature, and the app suddenly crashed. It make me frustrated and can't trust the app.

Can we auto save the data to local storage and let user load them if necessary?

Thanks.

**Comment by Pixelycia** [comment]
> > Hi,
> > Thanks for building such a talented application. I love the idea of fractal workspace of text links.
> > When I was playing with Neurite, I met two times of data loss accidentally. I accidentally close the browser tab by clicking the close tab shortcut I set before first time. Then I try to explorer the local ai feature, and the app suddenly crashed. It make me frustrated and can't trust the app.
> > Can we auto save the data to local storage and let user load them if necessary?
> > Thanks.
> 
> This all definitely an important next step for Neurite. You should be able to save your networks by using the save tab. However, I would not yet trust it to fully store your data long term *yet. Saving still needs work. Keep backups in .txt files, or download your saved networks.
> 
> Also, for installing the local models, I have not had the crashing issue. If you have a console error to share, that would be helpful. Could relate to trying to install a model that is too big for you vram.

Today at first I acidentally refreshed my page and one hour later my laptop felt to sleep and after wakeup refreshed my browser's tab automatically - so I lost my job twice. IMO, this is no good to not to cache at least last last application state if the application is a webpage.

**Comment by Pixelycia** [comment]
I can help with "temporary" (permanent?) solution, at least I will do it for myself and for just in case will make a pull request to this repo
