### ISSUE TITLE
Add File UX

### ISSUE THREAD

**Issue by twilwa** [satellitecomponent/Neurite#49]
Initial thought: I'd like to upload a PDF, I wonder if neurite could make a nice little fractal graph of interesting points for me to add to. Let me test it on the hosted version quickly -- [navigate to neurite.network, looking for 'upload file'. think the 'box-with-up-arrow' icon is most intuitive]
initiated an ask-for-support after that point before exploring more on my own, drag-and-drop pdf doesn't exhibit expected behavior (add PDF as node on graph), instead the PDF opens in a new browser tab on:
Chrome Version 126.0.6478.17 (Official Build) beta (64-bit)
I have a lot of extensions installed, so that may cause issues. Will test on some other browsers.
Failing import; alternative method is copy-paste text using the Link icon in the top-left. Possibly, when adding a link from the local filesystem, route the document through something like r.jina.ai or firecrawl.dev or jsondr.com depending on the required object type and insert the wget (wget @ url that only contains text content should deliver a text file with the content inside, i think?) into text field as node on graph

General 'add file' UX tracking issue, feel fee to drop of thoughts or interesting information. Once I have some bandwidth I may work on a PR for some of these potential ideas/fixes.

**Comment by satellitecomponent** [comment]
Good to be aware that drag and drop is behaving inconsistently. I have seen the issue, but it is not fully addressed.

An upload file button would be an easy addition, so I can try to add it in the next release.

**Comment by satellitecomponent** [comment]
commit 0264c86 should address these issues.
